apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:masters
      rolearn: arn:aws:iam::919309177960:role/UdacityFlaskDeployCBKubectlRole
      username: build
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::919309177960:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-1MF3E12WNA8VX
      username: system:node:{{EC2PrivateDNSName}}
kind: ConfigMap
metadata:
  creationTimestamp: "2022-01-10T19:11:09Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1581"
  uid: dba457b6-bd23-49b1-8517-c1a236d50049
